### ISSUE TITLE
Inventory BUG

### ISSUE THREAD

**Issue by BexiPE** [CookieSoftware/TSP#23]
The bug you can see on the Video:

Link: https://youtu.be/l_sdF6J_Zx4

**Comment by RateekMCPE** [comment]
Without knowing your Tesseract version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by BexiPE** [comment]
DEFUQ -.-

**Comment by andris155** [comment]
This is a plugin issue not Tesseract (?)

**Comment by BexiPE** [comment]
It is Tesseract 😑

**Comment by armagadon159753** [comment]
Have you any error display on console?

**Comment by BexiPE** [comment]
No😕

**Comment by andris155** [comment]
Debug enabled?

**Comment by CookieCode** [comment]
I think... this is your plugin...

**Comment by BexiPE** [comment]
Yes, Imthink that too.
