### ISSUE TITLE
MCPE 1.1 phar?

### ISSUE THREAD

**Issue by MalakasPlayzMC** [CookieSoftware/TSP#26]
I need a phar of 1.1. So I am giving you the idea to make gitlab to be able to download the latest build

**Comment by CookieCode** [comment]
You don't need the .phar file ! Just put the src at the same place .

**Comment by MalakasPlayzMC** [comment]
Thank you very much! I didn't know how to create a .phar file with DevTools...
Lol

**Comment by BrianZP** [comment]
Should I make a PR for the necessary files needed for CircleCI automatic .phar building?

**Comment by MalakasPlayzMC** [comment]
Why not...

**Comment by BexiPE** [comment]
I have createt a new Phar.
Link: https://www.dropbox.com/s/jggba5rsprpc3yn/Tesseract_1.3.0.phar?dl=0

**Comment by BexiPE** [comment]
If have a src on your Server make whit Devtools /makeserver

**Comment by BexiPE** [comment]
#26 Closed

**Comment by TacosYum** [comment]
Try https://pmt.mcpe.fun/
