### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by eru12** [CookieSoftware/TSP#28]
Items can be removed from items other than items in the item frame.

**Comment by CookieCode** [comment]
Explain, you have video or screens ? Error in console ?

**Comment by eru12** [comment]
https://youtu.be/WVqPlFDOis0
Cleak the link

**Comment by andris155** [comment]
Same problem

**Comment by andris155** [comment]
Iprotector not protect item frame. I don't know how to fix.

**Comment by BrianZP** [comment]
@eru12 This is not an issue related to TSP at all. It's an plugin issue and so should be closed. Try removing the protection from that area and then you can put back items in the item frame. Further there is this plugin which I use that protects the items within the item frame from players.
