### ISSUE TITLE
SendTitle is to fast!

### ISSUE THREAD

**Issue by BexiPE** [CookieSoftware/TSP#32]
**Problem description**

- If I send a Title it to fast down.

**Steps to reproduce the issue**
- Send a Title and see

**OS and versions**

Tesseract Version: 1.3.0 
PHP: 7.0.19
Game version: 1.1.0.55
Server host: Localhost

**Comment by BexiPE** [comment]
When the Bug is fixed?

**Comment by armagadon159753** [comment]
This comes from the Player.php

**Comment by BexiPE** [comment]
Why this issue is Closed? The bug is not fixed...
