### ISSUE TITLE
Fix FloatingTextParticle

### ISSUE THREAD

**Issue by majovec** [CookieSoftware/TSP#36]
Dont work FloaingTextParticle

**Comment by wiligangster** [comment]
Ok I fix this.

**Comment by majovec** [comment]
pleasse need

**Comment by opkiler22789** [comment]
+1

**Comment by opkiler22789** [comment]
@CookieCode The text is not displayed and the shadow is:
<img width="960" alt="applicationframehost_2017-06-20_08-52-35" src="https://user-images.githubusercontent.com/17113289/27318834-fed24bfe-5596-11e7-96f7-eea5785e0214.png">

**Comment by opkiler22789** [comment]
fixing in #50

**Comment by MasterOfTheRealm** [comment]
Thanks
