### ISSUE TITLE
SuperXing eat Banana

### ISSUE THREAD

**Issue by SuperXingKong** [CookieSoftware/TSP#38]
# I am a spammer

**Comment by shdudwns** [comment]
No!

**Comment by wiligangster** [comment]
Stop spam issue Kong.

**Comment by SuperXingKong** [comment]
Plz don't copy GenisysPro xD

**Comment by wiligangster** [comment]
I COPY YOUR CHEAT SOFTWARE XDDDD ?!!!

**Comment by majovec** [comment]
FUCKING SPAM @SuperXingKong  sorry

**Comment by wiligangster** [comment]
ME COPY !?? LOOK MY COMMIT STOP SAY SHIT

**Comment by SuperXingKong** [comment]
How do you explain this?
https://github.com/CookieSoftware/TSP/commit/208768c9ee193c30d051afed4c4927fe0956c7a2#diff-aaee4f21778267b6cafc6c388a281966L15

**Comment by wiligangster** [comment]
I HAVE FIXED CLASSIC UI

**Comment by wiligangster** [comment]
WTF ? Cookie?

**Comment by SuperXingKong** [comment]
He said he wanna join GenisysPro and he has been a member in our team already.

**Comment by SuperXingKong** [comment]
It's just a reminder. Sorry for my anger :

**Comment by wiligangster** [comment]
I will redo the code of Cookie. And make it better

**Comment by SuperXingKong** [comment]
Well

**Comment by MasterOfTheRealm** [comment]
Oh God...

**Comment by wiligangster** [comment]
?
