### ISSUE TITLE
Some sounds not work

### ISSUE THREAD

**Issue by andris155** [CookieSoftware/TSP#4]
#### Problem description

Some sounds not work

#### Steps to reproduce the issue

Block place, water, bow etc...

#### OS and versions

* Tesseract Version: 1.3.0 Unity
* PHP: 7.0.17
* Server OS: Windows 10
* Game version: 1.1.0.55
* Server host: My PC
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by CookieCode** [comment]
I'm currently working on it! Thanks for reporting this bug !
