### ISSUE TITLE
mmp

### ISSUE THREAD

**Issue by WadeHandlebar** [CookieSoftware/TSP#41]
What's this mmp?

**Comment by MasterOfTheRealm** [comment]
Mmp? Please Specify

**Comment by SuperXingKong** [comment]
Plz change my issue's title

**Comment by SuperXingKong** [comment]
#38

**Comment by Crypt97** [comment]
Do not think the main thing is to have at least one usable server file that I care about where the god is from

**Comment by SuperXingKong** [comment]
https://github.com/GenisysPro/GenisysPro @Crypt97 Watch this repo

**Comment by majovec** [comment]
cookie please block @SuperXingKong

**Comment by majovec** [comment]
@SuperXingKong you act like a little girl....

**Comment by Sinner168** [comment]
mmp=妈卖皮

**Comment by wiligangster** [comment]
Okep SuperKong shit blocked.

**Comment by majovec** [comment]
thanks he is stupid

**Comment by wiligangster** [comment]
It's a noob + copy / paste code from Genisys / PMMP

**Comment by majovec** [comment]
yes 
all pocketmine software is copy from old PocketMine-MP

**Comment by wiligangster** [comment]
Banned Dong King Kong

**Comment by majovec** [comment]
I don't understand why this fixes  (sorry my english is bad )
