### ISSUE TITLE
List your thefts

### ISSUE THREAD

**Issue by SuperXingKong** [CookieSoftware/TSP#42]
# No.1 ResourcePack
## PROOF: https://github.com/CookieSoftware/TSP/commit/208768c9ee193c30d051afed4c4927fe0956c7a2#diff-aaee4f21778267b6cafc6c388a281966L15

# No.2 BinarySteam
## All packets handle were copid from old GenisysPro, But you didn't mention it

# No.3 Folder-Plugin-Loader
## PROOF: https://github.com/CookieSoftware/TSP/commit/208768c9ee193c30d051afed4c4927fe0956c7a2#diff-68274b6a783228c83631aaf9dee49327R33

# Plz redo it by yourself

**Comment by Crypt97** [comment]
Do not think the main thing is to have at least one usable server file that I care about where the god is from

**Comment by wiligangster** [comment]
Waiit ? It's Genysis and not your software you copy paste Genisys lmaoo

**Comment by SuperXingKong** [comment]
Check your config version
Genisys don't have options like Folder-Plugin-Loader
