### ISSUE TITLE
Server crash and lagg (telkek = plotworld) (Chunk could not be converted to string)

### ISSUE THREAD

**Issue by andris155** [CookieSoftware/TSP#44]
#### Problem description

My server lagging and crash. Chunk unload bug (?)
https://timings.pmmp.io/?url=24881998

#### Steps to reproduce the issue

Run server 3-4 hours.

#### OS and versions

* TSP Version: https://github.com/CookieSoftware/TSP/tree/2d91b5e346d28b659b8175bb70ee2e866dd78c6c
* PHP: 7.0.18
* Server OS: Ubuntu 16
* Game version: 1.1.0.55
* Server host: VGH.hu
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Tesseract Crash Dump Sat Jun 17 23:11:22 CEST 2017

Error: Object of class pocketmine\level\format\Chunk could not be converted to string
File: /src/pocketmine/utils/BinaryStream
Line: 71
Type: E_RECOVERABLE_ERROR

Code:
[62] 		}elseif($len === true){
[63] 			$str = substr($this->buffer, $this->offset);
[64] 			$this->offset = strlen($this->buffer);
[65] 			return $str;
[66] 		}
[67] 		return $len === 1 ? $this->buffer{$this->offset++} : substr($this->buffer, ($this->offset += $len) - $len, $len);
[68] 	}
[69] 
[70] 	public function put($str){
[71] 		$this->buffer .= $str;
[72] 	}
[73] 
[74] 	public function getBool() : bool{
[75] 		return (bool) $this->getByte();
[76] 	}
[77] 
[78] 	public function putBool($v){
[79] 		$this->putByte((bool) $v);
[80] 	}
[81] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Tesseract version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux 37-17-172-57 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64
PHP version: 7.0.18
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 15 minutes 37 seconds
Number of loaded worlds: 7
Players online: 9/60

Loaded plugins:
StaffChat 1.1.0 by Thunder33345 for API(s) 2.0.0, 3.0.0-ALPHA4, 3.0.0-ALPHA5
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
ClearChat 1.0.0 by  for API(s) 1.14.0
blockMCPE14 1 by https://vk.com/ifreeze_dev for API(s) 2.0.0
AntiBotPE 1.1 by luca28pet for API(s) 2.0.0
ServerAuth 2.13 by EvolSoft for API(s) 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
AntiAbusiveEnchants 1 by SavionLegendZzz for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
PurePerms 1.4.0-INDEV by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0, 2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
MineMarket 0.1.0 by  for API(s) 1.0.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
WorldEditPotato 1.5 by HuaYoyu for API(s) 2.0.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.1.0, 2.0.0
Alias 2 by ZacHack for API(s) 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 3.0.0, 2.0.0, 2.1.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.4.1 by 64FF00 for API(s) 1.13.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
MyPlot 1.1.4 by Wiez, Exxarion, jasonwynn10 for API(s) 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
```

**Comment by wiligangster** [comment]
PACKET PACKET PACKET ...

**Comment by armagadon159753** [comment]
Can make in-game /statue and send screen

**Comment by andris155** [comment]
Server status ----
18.06 13:24:13 [Server] INFO Player count: 27/60
18.06 13:24:13 [Server] INFO Uptime: 9 hours 24 minutes 1 seconds
18.06 13:24:13 [Server] INFO Average TPS: 12.48 (90.53%)
18.06 13:24:13 [Server] INFO Current TPS: 3.86 (100%)
18.06 13:24:13 [Server] INFO Network upload: 2345338.79 kB/s
18.06 13:24:13 [Server] INFO Network download: 749154.12 kB/s
18.06 13:24:13 [Server] INFO Thread count: 6
18.06 13:24:13 [Server] INFO Main thread memory: 376 MB.
18.06 13:24:13 [Server] INFO Total memory: 874 MB.
18.06 13:24:13 [Server] INFO Total virtual memory: 1,530 MB.
18.06 13:24:13 [Server] INFO Heap memory: 14 MB.
18.06 13:24:13 [Server] INFO Maximum memory (system): 1,530 MB.
18.06 13:24:13 [Server] INFO World "spawn": 1,080 chunks, 22 entities, 941 tiles. Time 1.09ms
18.06 13:24:13 [Server] INFO World "nether": 0 chunks, 0 entities, 0 tiles. Time 0.01ms
18.06 13:24:13 [Server] INFO World "spawnworld": 43 chunks, 0 entities, 241 tiles. Time 8.92ms
18.06 13:24:13 [Server] INFO World "szabad2": 610 chunks, 19 entities, 305 tiles. Time 1.31ms
18.06 13:24:13 [Server] INFO World "telkek": 1,108 chunks, 5 entities, 4,495 tiles. Time 159.59ms
18.06 13:24:13 [Server] INFO World "eventworld": 9 chunks, 0 entities, 1 tiles. Time 0.01ms
18.06 13:24:13 [Server] INFO World "end": 9 chunks, 0 entities, 20 tiles. Time 0.01ms

**Comment by andris155** [comment]
slow VPS. :(
