### ISSUE TITLE
Code stealers

### ISSUE THREAD

**Issue by caspervanneck** [CookieSoftware/TSP#46]
I know its open  soarce but give some credits to genisyspro

**Comment by wiligangster** [comment]
Banned again skids

**Comment by wiligangster** [comment]
0% credits What open sources ??? Give me link skids

**Comment by caspervanneck** [comment]
@wiligangster wow your a dick

**Comment by caspervanneck** [comment]
github shult ben you and

**Comment by wiligangster** [comment]
Skiiids lifee

**Comment by wiligangster** [comment]
Learn english lol You talk like a shit

**Comment by caspervanneck** [comment]
lets we  talk it out for that its geting worst

**Comment by caspervanneck** [comment]
@wiligangster @CookieCode i dident know its a Tesseract fork

**Comment by caspervanneck** [comment]
i get the rong info

**Comment by caspervanneck** [comment]
so sorry

**Comment by wiligangster** [comment]
Yep it's a fork of Tesseract do you know how to read description ? Oh ?? I know you need learn english because your english is Bad and broken

**Comment by caspervanneck** [comment]
@wiligangster I can english but not on my phone

**Comment by wiligangster** [comment]
You must consult an autistic speech therapist.

**Comment by caspervanneck** [comment]
wow stop it just .....

**Comment by wiligangster** [comment]
talk to me bad then? You say shit about our software

**Comment by caspervanneck** [comment]
if you hate autistic poeple

**Comment by wiligangster** [comment]
The Autistic of your kind I help them have a good treatment.
