### ISSUE TITLE
Is it possible to add this function?

### ISSUE THREAD

**Issue by shdudwns** [CookieSoftware/TSP#51]
Monster AI function and monster is a hitting function

**Comment by MasterOfTheRealm** [comment]
Mob AI can be super laggy

**Comment by shdudwns** [comment]
Monster AI function and monster is a hitting function

**Comment by shdudwns** [comment]
@MasterOfTheRealm

**Comment by shdudwns** [comment]
Leave a commenthttps://github.com/BlueLightJapan/BlueLight/tree/Re-create/src/pocketmine/entity
