### ISSUE TITLE
When you TP into another world chunk not load

### ISSUE THREAD

**Issue by Iktaniyalol** [CookieSoftware/TSP#53]
* TSP Version: 1.3.0 CS
* PHP: 7.0.9
* Server OS: Linux
* Game version: 1.1.0.55
* Server host: VDS
When I tp in another world something command or by use mini-game table nothing not load. It remains the same map, but you seem to be on another map. Test it please.
P.S. When you go to nether by portal - nether chunk load and see

**Comment by CookieCode** [comment]
Try to TP you without any plugins (with your teleportation plugins)

**Comment by wiligangster** [comment]
Unload / load Chunk please
