### ISSUE TITLE
How to off CheckMovement?

### ISSUE THREAD

**Issue by Iktaniyalol** [CookieSoftware/TSP#55]
* TSP Version: 1.3.0 CS
* PHP: 7.0.9
* Server OS: Linux
* Game version: 1.1.0.55
* Server host: VDS
"Player move wrongly" is very flood message. How to off this?

**Comment by armagadon159753** [comment]
![screenshot_2017-06-21-16-46-03](https://user-images.githubusercontent.com/25569806/27390257-2471990e-56a1-11e7-9156-e7e12427b1ca.png)
 
Pocketmine.yml set to true to desiable roolback

**Comment by Iktaniyalol** [comment]
Thank you
