### ISSUE TITLE
Crash onJoin!

### ISSUE THREAD

**Issue by XDqrkneZ** [CookieSoftware/TSP#60]
#### Steps to reproduce the issue

I crash when i join!
#### OS and versions

* TSP Version: 1.4.0 Revolution
* PHP: 7.0.3
* Server OS: LINUX
* Game version: 1.1.1
* Server host: OVH
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by XDqrkneZ** [comment]
FIXED! (NOT SO). I removed PurePerms and i dont crash anymore

**Comment by armagadon159753** [comment]
Make you sure  you are using mast purperm on poggit pmmp
